on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Initialize Go modules
      run: go mod init github.com/JokerTrickster/data_structure

    - name: Setup Go modules
      run: go mod download

    - name: Echo current directory
      run: echo "Current directory is $(pwd)"

    - name: Calc coverage
      run: |
        cd src
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov