on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Initialize Go modules
      run: go mod init github.com/JokerTrickster/data_structure

    - name: Setup Go modules
      run: go mod download

    - name: Echo current directory
      run: echo "Current directory is $(pwd)"
    - name: Run Unit tests
      run: |
        cd src
        go test -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github